# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Justin/Lab4_Part3/Lab4_Part3.cache/wt [current_project]
set_property parent.project_path C:/Users/Justin/Lab4_Part3/Lab4_Part3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Justin/Lab4_Part3/Lab4_Part3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/sources_1/new/clkdiv.v
  C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/sources_1/new/hexto7segment.v
  C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/sources_1/new/time_mux_state_machine.v
  C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/sources_1/new/time_multiplexing_main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Justin/Lab4_Part3/Lab4_Part3.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top time_multiplexing_main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef time_multiplexing_main.dcp

catch { report_utilization -file time_multiplexing_main_utilization_synth.rpt -pb time_multiplexing_main_utilization_synth.pb }
